# Generated by Django 3.2.12 on 2022-02-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/')),
                ('Cname', models.CharField(max_length=100)),
                ('CInstructor', models.CharField(max_length=100)),
                ('Cduration', models.CharField(max_length=100)),
                ('Accessibility', models.CharField(max_length=100)),
                ('Cost', models.IntegerField()),
            ],
        ),
    ]
