# Generated by Django 3.2.12 on 2022-03-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_upload_ctopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('img', models.ImageField(upload_to='uploads/')),
                ('Cname', models.CharField(max_length=100)),
                ('CInstructor', models.CharField(max_length=100)),
                ('Cduration', models.CharField(max_length=100)),
                ('Ctopics', models.CharField(max_length=100)),
                ('Accessibility', models.CharField(max_length=100)),
                ('Cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('pid', models.IntegerField()),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
    ]
